# Localhost configuration for testing
#Uncomment the following lines to use the localhost server
# host = "localhost"
# port = "5432"
# dbname = "test_db"
# user = "new_user"
# password = "new_password"

# Production configuration for RDS
host = "tgr-main.c7ceuqo0a17n.us-west-1.rds.amazonaws.com"
port = "5432"
dbname = "tgr-main" # This should be your actual RDS database name, if different
user = "postgres"  # Your RDS username
password = "theDBpassword100"  # Your RDS password

app_password = "GoldyNugs"

payment_provider = "bmac"
