host = "localhost"
port = "5432"
dbname = "refactor_db"
user = "new_user"
password = "new_password"

app_password = "GoldyNugs"

OPENAI_API_KEY = "sk-None-L50kIbRGLQypW0SESC4OT3BlbkFJYjxD5kOz8rdk3xBlVop0"

payment_provider = "bmac"
