[firebase]
type = "service_account"
project_id = "thegrowersresource-1f2d7"
private_key_id = "7101b02dc43ae48224eac98b0b5081055993f722"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDEXhsAPNi9UzCm
5+8/CuXcAOgnsiyKM/kmDPZ0DVMIKJmUhMoaVqr1QHhtiwPywdRQqf62mgu0NMI0
...
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-hj18n@thegrowersresource-1f2d7.iam.gserviceaccount.com"
client_id = "111649934056391261418"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-hj18n%40thegrowersresource-1f2d7.iam.gserviceaccount.com"
