[firebase]
type = "service_account"
project_id = "thegrowersresource-1f2d7"
private_key_id = "7101b02dc43ae48224eac98b0b5081055993f722"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDEXhsAPNi9UzCm
5+8/CuXcAOgnsiyKM/kmDPZ0DVMIKJmUhMoaVqr1QHhtiwPywdRQqf62mgu0NMI0
IAyUdnZZpZIiCUc15xTryt5Rxmc/ycnD9lLKHwkS9nYvyd6OkVf9TuIAlVuxQLiW
WsRnoahd8UJvrAiUcZl4Dh8YWAflLeO1COgXs+uYGk131glqhnalYCm5LpvvG0+8
jEHazHUJytrs/8fT11TvLesAMqzLZIq2X2UdnXJsnD+B9pzHXZ9Kh/M8TVGkWgSV
lAwltuU7v82dHaiCpm7LqJRWrGFyW2DNWSBw3tz5ExZj13v958MAiIJC5lw9k2Vh
doitI7u5AgMBAAECggEACDZ7YJ4q3ng9P63RpsxY4sOy8f4UuM8Fq569LAtmnp+8
FKcdIM7hJZLFtqcqyhtrOthxS8fTl3zhZna0r/zoZEV1gDDtJob8rAP3Gmp25QcW
hjimK8fyhDWEqekCgun3SSPkdevJQveXAMrZDhCHzy4I/kyuqy65IXlNuaHs6pvW
9DGh6EJsiDgerUoktkbVRY4cqnlVYh9GBCWjp5n2S+d7ljyqdWtLimlFgStqWJpb
hDmWG01u7iJ7nMVD2HjypbB0IPJb2wHo2wDICl4qxoxlFVeQxmS9LXodnA18Aonp
HTLv6a/dvVz7yWHYmXbZ1KhAaUpnFwmFRGLhTZI+hQKBgQDrfjIX0qP5r8GSdIth
dcJ5w3bJOMKw+MUQX9Gr6FHv6LxsFxWMjiawfJaGudy7yAdhbYpLrrttU3oyIBvW
ctipkgfbpOOy+mlB7ThMwD8czzOaWI0DsFr2X9QsEY2fyLPP0baXQNzd3QaoQTW7
CWRO2FCyvYxJMMEJiN74v5YllwKBgQDVd7HplyB+4FjVZ+WB54u2PQfloWP+EOTB
/Bh3wfK7H/TL4n/5g1rQjuh3wOElx835IYC7NNVL1vg79qWTFHf3b4xYF1ICSKSn
rJhbooelnRkToYcDV7Xjnsv+V7KBB7Za/U+uxJ9Uc93/hQNC7yXXw4dgy5p7hQ85
lAZz9dBzLwKBgQCIgVU+M+6zHGsjnwTwUJeTh3dCuvE4LmvkyvY6JOfiHlGiglsO
Z5QLt5x1qiVGgHOuyRViO34PqFTr22rnixkGaky9yD3pEHiVK5H4A3RSGdV6wZu0
KLUBnZjalq42kduROqoR0Rp2TNnADFS9/3qyrXdRtMgt4OH0ye8d18iMLwKBgQDB
t0JjuXqKyOq0lvlGXqqBsXbGIySLvibqBuzpWL7+oyxSDXSXKGW0V8uMSSPIVj6L
s6SPvo1FqopQWC6/f1ay266fjmIkommRo+YLWj4Aw8Sq9O2B0gnEyylR4aGiyC3q
+m9iKRpx2EgAhmOETWOpHs5uv7WsG/7KAJOujcchjwKBgQCNp02sCAKMEZE19Hr2
6Bx4ncEM6ssFHsZQN7rW1EhzVvsz+B/u743AHmNWFlZdQ2I79BKdHhLRJMi67Bts
4yxix//BuljXoLmJbmQp6hKMY6MYCisi4nYN/XAPWIZPQm7eOfFl7IXQBG7O3Qvw
GDl+qqgnon7Wb+F2Ai/AATD7MQ==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-hj18n@thegrowersresource-1f2d7.iam.gserviceaccount.com"
client_id = "111649934056391261418"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-hj18n@thegrowersresource-1f2d7.iam.gserviceaccount.com"

